---
title: "Homework 1"
output: html_notebook
---

Create a 5 by 10 matrix of random integers
```{r}
m <- matrix(sample.int(100,size=50),nrow=5,ncol=10)
```

Define column names as cond1, cond2, cond3, cond4, cond5, ctrl1, ctrl2, ctrl3, ctrl4, ctrl5
```{r}
cnames <- c("cond1", "cond2", "cond3", "cond4", "cond5",
           "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
colnames(m) <- cnames
```

Define row names as gene1, gene2, gene3 ...
```{r}
rnames <- c("gene1", "gene2", "gene3", "gene4", "gene5")
rownames(m) <- rnames
```

Compute the fold change for each gene
```{r}
# Following the pipeline of DESeq2
coldata <- data.frame(genes = rnames,
                      conditions = cnames)
coldata$conditions <- factor(substr(cnames, start = 1, 
                                    stop = nchar(cnames[1]) - 1))
dds <- DESeq2::DESeqDataSetFromMatrix(countData = m,
                                      colData = coldata,
                                      design = ~ conditions)
dds$conditions <- factor(dds$conditions, levels = c("cond","ctrl"))
dds <- DESeq(dds)
resultsNames(dds)

# Calculate log2FoldChange of control vs condition
res <- results(dds, contrast=c("conditions","cond","ctrl"))
res
```





